{{- range .Values.components }}

{{- $component := . }}

{{- range .instances }}

apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ $component.componentName }}-{{ .name }}-config

data:

{{- range $k,$v := $component.commonConfig }}
  {{ $k }}: {{ $v | quote }}
{{- end }}

{{- range $k,$v := .config }}
  {{ $k }}: {{ $v | quote }}
{{- end }}

---
{{- end }}
{{- end }}